[package]
name = "dspi-tui"
description = "The DSPi terminal interface"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
dspi-proto.workspace = true
dspi-transport.workspace = true
dspi-session.workspace = true
dspi-cmd.workspace = true
ratatui = "0.29"
crossterm = "0.28"
unicode-width = "0.2"
