//! Generates Rust constants from the vendored DSPi firmware headers.
//!
//! The headers in `firmware/` are the source of truth for the protocol; nothing
//! in this crate transcribes an opcode, a range, or a struct size by hand. A
//! firmware bump is therefore a file copy plus a build, and the coverage test in
//! `tests/coverage.rs` reports exactly what changed.
//!
//! This is a purpose-built scanner, not a C parser. It handles the subset of C
//! the headers actually use for constants, and it is deliberately loud about
//! anything it cannot interpret rather than guessing.
//!
//! Platform-conditional constants (`NUM_CHANNELS` and friends, which differ
//! between RP2040 and RP2350 via `#if PICO_RP2350`) are **deliberately not
//! emitted**. Device topology is discovered at connect, never compiled in; see
//! REDESIGN_SPEC.md 3.2 mechanism 1. The scanner detects conflicting
//! redefinitions and skips them, so a new platform-conditional constant cannot
//! accidentally become a hardcoded assumption.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

const HEADERS: &[&str] = &[
    "config.h",
    "bulk_params.h",
    "control_surfaces.h",
    "psybass.h",
    "upmix.h",
    "siggen.h",
];

/// Prefixes we lift into generated `u16` constants, with the module they land in.
const DEFINE_GROUPS: &[(&str, &str)] = &[
    ("REQ_", "opcodes"),
    ("WIRE_", "wire"),
    ("CS_", "cs"),
    ("PIN_CONFIG_", "status"),
    ("PRESET_", "status"),
    ("FLASH_", "status"),
    ("SIGGEN_", "siggen"),
    ("UPMIX_", "upmix"),
    ("FILTER_", "filter"),
    ("XOVER_", "filter"),
    ("MAX_XOVER_", "filter"),
];

/// Float ranges and defaults, lifted as `f32`.
const FLOAT_PREFIXES: &[&str] = &["PSYBASS_", "UPMIX_", "LOUDNESS_", "LEVELLER_"];

fn main() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("firmware");
    for h in HEADERS {
        println!("cargo:rerun-if-changed=firmware/{h}");
    }
    println!("cargo:rerun-if-changed=firmware/PROVENANCE.toml");
    println!("cargo:rerun-if-changed=build.rs");

    let mut ints: BTreeMap<String, (i64, String, String)> = BTreeMap::new();
    let mut floats: BTreeMap<String, (f64, String)> = BTreeMap::new();
    let mut conflicts: Vec<String> = Vec::new();

    for header in HEADERS {
        let path = dir.join(header);
        let text = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("cannot read vendored header {}: {e}", path.display()));

        for raw in text.lines() {
            let Some((name, value)) = parse_define(raw) else {
                continue;
            };

            if let Some(group) = group_for(&name)
                && let Some(v) = parse_int(value)
            {
                match ints.get(&name) {
                    // Platform-conditional redefinition: refuse to emit.
                    Some((prev, _, _)) if *prev != v => {
                        conflicts.push(name.clone());
                    }
                    Some(_) => {}
                    None => {
                        ints.insert(name, (v, group.to_string(), header.to_string()));
                    }
                }
                continue;
            }

            if FLOAT_PREFIXES.iter().any(|p| name.starts_with(p))
                && let Some(v) = parse_float(value)
            {
                floats.entry(name).or_insert((v, header.to_string()));
            }
        }
    }

    // A conflicting definition is platform-dependent by construction. Drop it so
    // it can never be mistaken for a fixed fact, and say so in the build log.
    for name in &conflicts {
        ints.remove(name);
        println!("cargo:warning=platform-conditional, not emitted: {name}");
    }

    let mut out = String::new();
    out.push_str(
        "// @generated by build.rs from the vendored firmware headers. Do not edit.\n\
         // Source of truth: crates/dspi-proto/firmware/ (see PROVENANCE.toml).\n\n",
    );

    emit_provenance(&dir, &mut out);

    // Group the integer constants into modules.
    let mut by_group: BTreeMap<&str, Vec<(&String, &i64, &String)>> = BTreeMap::new();
    for (name, (v, group, header)) in &ints {
        by_group
            .entry(group.as_str())
            .or_default()
            .push((name, v, header));
    }

    for (group, items) in &by_group {
        let _ = writeln!(out, "pub mod {group} {{");
        for (name, v, _) in items {
            let ty = if **v >= 0 && **v <= u8::MAX as i64 && name.starts_with("REQ_") {
                "u8"
            } else if **v >= 0 && **v <= u16::MAX as i64 {
                "u16"
            } else {
                "i32"
            };
            let _ = writeln!(out, "    pub const {name}: {ty} = {v};");
        }
        let _ = writeln!(out, "}}\n");
    }

    if !floats.is_empty() {
        out.push_str("pub mod ranges {\n");
        for (name, (v, _)) in &floats {
            let _ = writeln!(out, "    pub const {name}: f32 = {v:?};");
        }
        out.push_str("}\n\n");
    }

    emit_opcode_table(&ints, &mut out);
    emit_wire_layout(&ints, &mut out);

    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join("generated.rs");
    std::fs::write(&dest, out).expect("write generated.rs");
}

/// `#define NAME VALUE  // comment` -> `(NAME, VALUE)`.
fn parse_define(line: &str) -> Option<(String, &str)> {
    let rest = line.trim().strip_prefix("#define")?;
    let rest = rest.trim_start();
    let split = rest.find(|c: char| c.is_whitespace())?;
    let (name, value) = rest.split_at(split);

    // Function-like macros are not constants.
    if name.contains('(') {
        return None;
    }

    let value = value.split("//").next().unwrap_or("");
    let value = value.split("/*").next().unwrap_or("").trim();
    if value.is_empty() {
        return None;
    }
    Some((name.to_string(), value))
}

fn group_for(name: &str) -> Option<&'static str> {
    DEFINE_GROUPS
        .iter()
        .find(|(prefix, _)| name.starts_with(prefix))
        .map(|(_, group)| *group)
}

/// Plain integer literals only. Anything parenthesised or computed is an
/// expression we refuse to evaluate, because a wrong guess would be silent.
fn parse_int(v: &str) -> Option<i64> {
    let v = v.trim().trim_end_matches('u').trim_end_matches('U');
    if let Some(hex) = v.strip_prefix("0x").or_else(|| v.strip_prefix("0X")) {
        return i64::from_str_radix(hex, 16).ok();
    }
    v.parse::<i64>().ok()
}

fn parse_float(v: &str) -> Option<f64> {
    let v = v.trim().trim_end_matches('f').trim_end_matches('F');
    if !v.contains('.') && !v.contains('e') && !v.contains('E') {
        return None;
    }
    v.parse::<f64>().ok()
}

fn emit_provenance(dir: &Path, out: &mut String) {
    let toml = std::fs::read_to_string(dir.join("PROVENANCE.toml")).unwrap_or_default();
    let field = |key: &str| -> String {
        toml.lines()
            .find(|l| l.trim_start().starts_with(key))
            .and_then(|l| l.split('=').nth(1))
            .map(|v| v.trim().trim_matches('"').to_string())
            .unwrap_or_else(|| "unknown".into())
    };
    let _ = writeln!(out, "/// The firmware revision these constants came from.");
    let _ = writeln!(out, "pub mod provenance {{");
    let _ = writeln!(out, "    pub const BRANCH: &str = {:?};", field("branch"));
    let _ = writeln!(out, "    pub const COMMIT: &str = {:?};", field("commit"));
    let _ = writeln!(out, "    pub const SHORT: &str = {:?};", field("short"));
    let _ = writeln!(
        out,
        "    pub const COMMITTED: &str = {:?};",
        field("committed")
    );
    let _ = writeln!(out, "}}\n");
}

/// Every `REQ_*` opcode as a `(name, value)` table. The coverage test walks this
/// and fails the build if an opcode is neither registered nor explicitly
/// excluded, which is what makes "controls every setting" checkable.
fn emit_opcode_table(ints: &BTreeMap<String, (i64, String, String)>, out: &mut String) {
    let reqs: Vec<_> = ints
        .iter()
        .filter(|(n, _)| n.starts_with("REQ_"))
        .map(|(n, (v, _, _))| (n.clone(), *v as u8))
        .collect();

    let _ = writeln!(
        out,
        "/// Every vendor opcode defined by the firmware, sorted by name.\n\
         pub const ALL_OPCODES: [(&str, u8); {}] = [",
        reqs.len()
    );
    for (name, v) in &reqs {
        let _ = writeln!(out, "    ({name:?}, 0x{v:02X}),");
    }
    out.push_str("];\n\n");
}

/// Section offsets for `WireBulkParams`, computed from the sizing constants
/// rather than transcribed, then checked against the firmware's own total.
fn emit_wire_layout(ints: &BTreeMap<String, (i64, String, String)>, out: &mut String) {
    let g = |k: &str| -> i64 {
        ints.get(k)
            .map(|(v, _, _)| *v)
            .unwrap_or_else(|| panic!("vendored headers no longer define {k}; update build.rs"))
    };

    let n_ch = g("WIRE_MAX_CHANNELS");
    let n_in = g("WIRE_MAX_INPUT_CHANNELS");
    let n_out = g("WIRE_MAX_OUTPUT_CHANNELS");
    let n_bands = g("WIRE_MAX_BANDS");
    let n_xover = g("WIRE_MAX_XOVER_BANDS");
    let n_pins = g("WIRE_MAX_PIN_OUTPUTS");
    let name_len = g("WIRE_NAME_LEN");

    // (name, size) in declaration order; sizes derive from the constants above.
    let sections: Vec<(&str, i64)> = vec![
        ("header", 16),
        ("global", 16),
        ("crossfeed", 16),
        ("legacy", 16),
        ("delays", 4 * n_ch),
        ("crosspoints", 8 * n_in * n_out),
        ("outputs", 12 * n_out),
        ("pins", 1 + n_pins + 2),
        ("eq", 16 * n_ch * n_bands),
        ("channel_names", n_ch * name_len),
        ("i2s_config", 16),
        ("leveller", 20),
        ("preamp", 4 * n_in),
        ("master_volume", 16),
        ("input_config", 16),
        ("lg_sound_sync", 16),
        ("user_volume", 16),
        ("dac_hw_mute", 16),
        ("crossovers", 16 * n_ch * n_xover),
        ("adat_config", 8),
        ("psybass", 24),
        ("upmix", 44),
    ];

    let mut offset = 0i64;
    let mut rows = String::new();
    for (name, size) in &sections {
        let upper = name.to_uppercase();
        let _ = writeln!(out, "pub const OFF_{upper}: usize = {offset};");
        let _ = writeln!(out, "pub const LEN_{upper}: usize = {size};");
        let _ = writeln!(rows, "    (\"{name}\", {offset}, {size}),");
        offset += size;
    }

    let _ = writeln!(
        out,
        "\n/// Total `WireBulkParams` size, derived from the header constants."
    );
    let _ = writeln!(out, "pub const BULK_SIZE: usize = {offset};");
    let _ = writeln!(
        out,
        "\n/// `(section, offset, len)` in declaration order.\n\
         pub const SECTIONS: [(&str, usize, usize); {}] = [\n{rows}];\n",
        sections.len()
    );
}
